#!/bin/bash

#compiles project if not compiled
if [ ! -d "out" ]; then
    echo "Compiling..."
    javac -d out src/**/*.java
fi

#executes the program
if [ "$1" ]; then
    java -cp out src.main.Application "$1"
else
    java -cp out src.main.Application
fi

