#!/bin/bash

SRC_DIR="src"
BIN_DIR="bin"
MAIN_CLASS="main.Application"

if [ ! -d "$BIN_DIR" ] || [ -z "$(find "$BIN_DIR" -name '*.class' 2>/dev/null)" ]; then
    echo "Compiling..."
    mkdir -p "$BIN_DIR"
    find "$SRC_DIR" -name "*.java" | xargs javac -d "$BIN_DIR"
fi

if [ "$1" ]; then
    java -cp "$BIN_DIR" "$MAIN_CLASS" "$1"
else
    java -cp "$BIN_DIR" "$MAIN_CLASS"
fi


